<a href="https://colab.research.google.com/github/MLBadrdeep/Classification/blob/main/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ---------------------------------------------------------------
# python best courses https://courses.tanpham.org/
# ---------------------------------------------------------------

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.11/dist-packages/numpy/version.py'>

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
np.full(10, np.nan)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 4.  How to find the memory size of any array (★☆☆)

In [7]:
x = np.array([1, 2, 3, 4, 5])
print(x.nbytes)

40


5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [13]:
vector = np.array([1, 2, 3, 4, 5])
reversed_vector = vector[::-1]
print(reversed_vector)

[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [15]:
x = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(x)
print(indices[0])

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
np.random.rand(3, 3, 3)

array([[[0.98200118, 0.77881327, 0.35844381],
        [0.26535344, 0.79888863, 0.13516929],
        [0.30618719, 0.79944514, 0.82818501]],

       [[0.09547752, 0.35780122, 0.84198899],
        [0.59342132, 0.49550877, 0.1611642 ],
        [0.66236008, 0.60466761, 0.37066176]],

       [[0.86819709, 0.43222059, 0.89405751],
        [0.61959155, 0.5729769 , 0.23250739],
        [0.7390923 , 0.67396394, 0.64506139]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
np.random.rand(10, 10)

array([[0.51059861, 0.74423672, 0.54869506, 0.37281481, 0.14871481,
        0.71715594, 0.98990948, 0.99322332, 0.20782757, 0.52539683],
       [0.79956839, 0.03039384, 0.13548225, 0.74672826, 0.12925858,
        0.99303501, 0.88341934, 0.40422384, 0.20627056, 0.2355451 ],
       [0.9495429 , 0.88281441, 0.88938955, 0.37998701, 0.76826354,
        0.18709528, 0.59433226, 0.86260428, 0.89724341, 0.43387766],
       [0.34597169, 0.26211757, 0.03040237, 0.69064125, 0.91254317,
        0.30855473, 0.43141943, 0.24584896, 0.8158362 , 0.61863762],
       [0.30607427, 0.31321857, 0.09847761, 0.60131481, 0.8487925 ,
        0.24032571, 0.02080516, 0.14776308, 0.73772706, 0.50660761],
       [0.56729807, 0.64799462, 0.6074312 , 0.42047001, 0.19651768,
        0.73413743, 0.30845423, 0.46115613, 0.66412301, 0.81480283],
       [0.03821238, 0.69093474, 0.9693722 , 0.93313649, 0.86852382,
        0.32168883, 0.51600865, 0.85388879, 0.71102889, 0.22217278],
       [0.55963121, 0.26266211, 0.9835484

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [19]:
np.random.rand(30)

array([0.73439897, 0.36936325, 0.69941564, 0.04277198, 0.8171461 ,
       0.40911412, 0.4291228 , 0.11550736, 0.01877182, 0.45859317,
       0.42537782, 0.3963675 , 0.03918712, 0.82956829, 0.65925606,
       0.34945086, 0.1444191 , 0.02604193, 0.90227437, 0.65736514,
       0.09642103, 0.68498028, 0.29901312, 0.54664799, 0.83083277,
       0.37160912, 0.64027277, 0.42598506, 0.21904528, 0.76456436])

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [20]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [21]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [22]:
np.nan
False
False
np.nan
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [23]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [24]:
np.zeros((8, 8), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [25]:
np.unravel_index(100, (6, 7, 8))

(np.int64(1), np.int64(5), np.int64(4))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [26]:
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [27]:
np.random.rand(5, 5)

array([[0.75951387, 0.88050074, 0.99817355, 0.11086508, 0.30680577],
       [0.74204928, 0.98795935, 0.72455173, 0.49262032, 0.46139038],
       [0.73284942, 0.08750692, 0.71342523, 0.53142815, 0.77894855],
       [0.72413861, 0.31876076, 0.38529374, 0.95325456, 0.46978657],
       [0.40954652, 0.67471718, 0.58935158, 0.34701803, 0.06256567]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [28]:
np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [29]:
np.random.rand(5, 3) @ np.random.rand(3, 2)

array([[0.81924861, 0.70666096],
       [1.02989279, 0.92478961],
       [1.49045464, 1.42588372],
       [1.04549997, 0.94082601],
       [1.59011291, 1.62862319]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [30]:
np.random.rand(10)

array([0.71789709, 0.59025343, 0.3306435 , 0.30335968, 0.82478337,
       0.75429742, 0.59321913, 0.14187433, 0.02412734, 0.84185373])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
np.sum(range(5), -1)

np.int64(10)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [32]:
np.array([1, 2, 3]) ** np.array([1, 2, 3])

array([ 1,  4, 27])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [33]:
np.array([np.nan]).astype(int).astype(float)

/tmp/ipython-input-699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [34]:
np.random.rand(10)

array([0.07362017, 0.96401791, 0.94057302, 0.56867169, 0.40139351,
       0.66459287, 0.13973732, 0.82418252, 0.70196297, 0.87791149])

#### 30. How to find common values between two arrays? (★☆☆)

In [35]:
np.array([1, 2, 3]) @ np.array([1, 2, 3])

np.int64(14)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [36]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [39]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [40]:
np.datetime64('today')

np.datetime64('2025-08-05')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [41]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [42]:
np.random.rand(10)

array([0.02008192, 0.78398174, 0.16090731, 0.58837808, 0.72877713,
       0.25472184, 0.20864121, 0.42565453, 0.36719954, 0.56677352])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [43]:
np.random.rand(10)

array([0.85658102, 0.35235854, 0.63911544, 0.62408327, 0.88881317,
       0.30538507, 0.96432826, 0.1736147 , 0.17859021, 0.90801162])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [44]:
np.random.rand(5, 5)

array([[0.847157  , 0.55466188, 0.86090853, 0.16546504, 0.10959308],
       [0.3063382 , 0.94692788, 0.64954013, 0.61224348, 0.16516608],
       [0.59699376, 0.42969332, 0.50729412, 0.44716262, 0.61142887],
       [0.96452881, 0.33278304, 0.9722412 , 0.73371196, 0.04050994],
       [0.23513341, 0.47230103, 0.60949717, 0.48029248, 0.41817205]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [45]:
np.random.rand(10)

array([0.85054158, 0.31961323, 0.82088592, 0.31839701, 0.39981928,
       0.76670238, 0.46504791, 0.00248921, 0.74351847, 0.17722671])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [46]:
np.random.rand(10)

array([0.29300255, 0.75538403, 0.11988123, 0.55298194, 0.28324842,
       0.25791335, 0.01117716, 0.26963981, 0.88888719, 0.55143333])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [49]:
np.sort(np.random.rand(10))

array([0.19436268, 0.20587836, 0.30024062, 0.47534845, 0.56188956,
       0.59070557, 0.80927088, 0.81664706, 0.89172389, 0.96335909])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [48]:
np.sum(np.random.rand(10))

np.float64(5.678407943538181)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [50]:
np.random.rand(10) == np.random.rand(10)

array([False, False, False, False, False, False, False, False, False,
       False])

#### 43. Make an array immutable (read-only) (★★☆)

In [53]:
np.random.rand(10).flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [54]:
np.random.rand(10, 2)

array([[0.32477224, 0.9062213 ],
       [0.19805078, 0.73293586],
       [0.19696778, 0.771024  ],
       [0.66031534, 0.70686442],
       [0.01743122, 0.01161323],
       [0.95136984, 0.08736976],
       [0.04827768, 0.95476891],
       [0.64231651, 0.1658954 ],
       [0.7800438 , 0.5594674 ],
       [0.93366904, 0.73657239]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [55]:
np.random.rand(10).argmax()

np.int64(4)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [58]:
n = 5
x = np.linspace(0, 1, n)
y = np.linspace(0, 1, n)
xx, yy = np.meshgrid(x, y)
dtype = [('x', 'f4'), ('y', 'f4')]
structured_array = np.array(list(zip(xx.ravel(), yy.ravel())), dtype=dtype)
print(structured_array)

[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [57]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
C = 1 / (X[:, np.newaxis] - Y[np.newaxis, :])
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [59]:
int_types = [np.int8, np.int16, np.int32, np.int64,
             np.uint8, np.uint16, np.uint32, np.uint64]
print("Integer types:")
for t in int_types:
    info = np.iinfo(t)
    print(f"{t.__name__}: min = {info.min}, max = {info.max}")
float_types = [np.float16, np.float32, np.float64]
print("\nFloat types:")
for t in float_types:
    info = np.finfo(t)
    print(f"{t.__name__}: min = {info.min}, max = {info.max}")

Integer types:
int8: min = -128, max = 127
int16: min = -32768, max = 32767
int32: min = -2147483648, max = 2147483647
int64: min = -9223372036854775808, max = 9223372036854775807
uint8: min = 0, max = 255
uint16: min = 0, max = 65535
uint32: min = 0, max = 4294967295
uint64: min = 0, max = 18446744073709551615

Float types:
float16: min = -65504.0, max = 65504.0
float32: min = -3.4028234663852886e+38, max = 3.4028234663852886e+38
float64: min = -1.7976931348623157e+308, max = 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [61]:
arr = np.arange(100)
np.set_printoptions(threshold=np.inf)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [62]:
vector = np.array([10, 22, 14, 3, 6, 29])
target = 13
closest_value = vector[np.argmin(np.abs(vector - target))]
print("Closest value:", closest_value)

Closest value: 14


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)